### ISSUE TITLE
Question: Supported Targets

### ISSUE THREAD

**Issue by Biztactix-Ryan** [jocover/esp32_u2f#6]
I see you say in there that USB OTG is the only thing required... 
That opens up a bunch of the ESPs, For instance the C3 etc.
Is there anything else needed? any hardware specific security functions? hmac etc?
I have some S3's coming, but I only have some older ESPs or the C3 on hand atm... So just thought I'd check.

**Comment by jocover** [comment]
esp32c3 only supports usb serial
fido2 requires usb hid support
so esp32c3 cannot be used

**Comment by Biztactix-Ryan** [comment]
Sorry about that, I must have mixed up the data sheets, I was sure it said the C3 or C6 was OTG... But they aren't ... Sorry mate.
